PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;

CREATE TABLE "new_Patient" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userCode" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "documentType" TEXT NOT NULL,
    "documentNumber" TEXT NOT NULL,
    "birthDate" DATETIME NOT NULL,
    "gender" TEXT,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "address" TEXT,
    "occupation" TEXT,
    "allergies" TEXT,
    "currentMedications" TEXT,
    "systemicDiseases" TEXT,
    "surgeries" TEXT,
    "pregnant" BOOLEAN NOT NULL DEFAULT false,
    "smoker" BOOLEAN NOT NULL DEFAULT false,
    "medicalNotes" TEXT,
    "lastDentalVisit" DATETIME,
    "reasonForConsultation" TEXT,
    "previousTreatments" TEXT,
    "brushingFrequency" TEXT,
    "flossing" BOOLEAN NOT NULL DEFAULT false,
    "bleedingGums" BOOLEAN NOT NULL DEFAULT false,
    "bruxism" BOOLEAN NOT NULL DEFAULT false,
    "dentalNotes" TEXT,
    "isInPain" BOOLEAN NOT NULL DEFAULT false,
    "painLevel" INTEGER NOT NULL DEFAULT 0,
    "painLocation" TEXT,
    "painDuration" TEXT,
    "painTrigger" TEXT,
    "painDescription" TEXT,
    "takesMedication" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

INSERT INTO "new_Patient" (
    "id",
    "userCode",
    "firstName",
    "lastName",
    "documentType",
    "documentNumber",
    "birthDate",
    "gender",
    "phone",
    "email",
    "address",
    "occupation",
    "allergies",
    "currentMedications",
    "systemicDiseases",
    "surgeries",
    "pregnant",
    "smoker",
    "medicalNotes",
    "lastDentalVisit",
    "reasonForConsultation",
    "previousTreatments",
    "brushingFrequency",
    "flossing",
    "bleedingGums",
    "bruxism",
    "dentalNotes",
    "isInPain",
    "painLevel",
    "painLocation",
    "painDuration",
    "painTrigger",
    "painDescription",
    "takesMedication",
    "createdAt",
    "updatedAt"
)
SELECT
    "id",
    UPPER(printf('%06X', "id")),
    "firstName",
    "lastName",
    "documentType",
    "documentNumber",
    "birthDate",
    "gender",
    "phone",
    "email",
    "address",
    "occupation",
    "allergies",
    "currentMedications",
    "systemicDiseases",
    "surgeries",
    "pregnant",
    "smoker",
    "medicalNotes",
    "lastDentalVisit",
    "reasonForConsultation",
    "previousTreatments",
    "brushingFrequency",
    "flossing",
    "bleedingGums",
    "bruxism",
    "dentalNotes",
    "isInPain",
    "painLevel",
    "painLocation",
    "painDuration",
    "painTrigger",
    "painDescription",
    "takesMedication",
    "createdAt",
    "updatedAt"
FROM "Patient";

DROP TABLE "Patient";
ALTER TABLE "new_Patient" RENAME TO "Patient";

CREATE UNIQUE INDEX "Patient_documentNumber_key" ON "Patient"("documentNumber");
CREATE UNIQUE INDEX "Patient_userCode_key" ON "Patient"("userCode");

PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
